### PR TITLE
Fix problematic default message_ttl on rabbitmq_federation

### LINKED ISSUE #26: Federation-upstream and message_ttl with no value
Hi,

If I don't provide a value for message_ttl, it sends the value 0 to RabbitMQ.

But the correct value is none.

Could you correct this?

Thanks

### PR DESCRIPTION
**Pull request by ahmadalli**
This fixes #26 by updating the underlying rabbit-hole package to `v2.13.0` which fixed this issue michaelklishin/rabbit-hole#230

### CODE REVIEW

**Comment by ahmadalli** [comment]
@cyrilgdn Would you please take a look at this PR?

**Comment by ahmadalli** [comment]
@cyrilgdn I've updated all packages by running `go get -u && go mod tidy` and after that `golangci-lint run` and tests ran without any problem. Would you please check again?

**Comment by ahmadalli** [comment]
@cyrilgdn Would you please take a look again?

**Comment by ahmadalli** [comment]
@cyrilgdn Would you please take a look again?

**Review by cyrilgdn — APPROVED** [review]
@ahmadalli Yes sorry for the delay

**Pull request merged**
