### PR TITLE
Force a new resource on every paramter change of a rabbitmq_shovel

### PR DESCRIPTION
**Pull request by akurz**
This fixes Issue #2 - shovels need to be completely recreated for any parameter change. I tested this in our setup with RMQ 3.8.21 and Terraform 1.1

### CODE REVIEW

**Comment by al-lac** [comment]
This would be really nice to have! Updates are currently failing for me when i change infos on the shovel.

**Comment by akurz** [comment]
I did not think about this @justinbaur because re-creating is realy fast and works fine. Would there be any advantage of doing an update of the shovel - like e.g. no restart of the shovel is needed?

**Comment by justinbaur** [comment]
After turning on the debug logging it seems that the API operation updates the shovel definition and restarts it.  The same log statement is printed for manually restarting the shovel and also updating via the API.
`2021-12-17 22:33:26.518 [debug] <0.1751.0> Shovel 'steves-shovel' has finished setting up its topology`

I've tested the update command on both version 3.7 and 3.8 which are used in the `testacc` script.

**Review by cyrilgdn — APPROVED** [review]
Hi,

Sorry for the response delay.... Better late than never :sweat_smile: 

@justinbaur After a few tests, there's a bug with your PR #28 , I'll comment it but will already apply/release this fix.

**Pull request merged**
